-- Table: public.aliquotas

create table public.aliquotas 
(
    CP_ALIQUOTAS     SERIAL PRIMARY KEY,
    ALIQ_DESCRICAO   character varying (30) NOT NULL,
    ALIQ_PERCENTUAL  numeric (15,2) NOT NULL,
    ALIQ_CODIGO      character varying (3) NOT NULL
);

--Dados: public.aliquotas

INSERT INTO ALIQUOTAS (CP_ALIQUOTAS,ALIQ_DESCRICAO,ALIQ_PERCENTUAL,ALIQ_CODIGO) VALUES (1,'3 %',3,'01');
INSERT INTO ALIQUOTAS (CP_ALIQUOTAS,ALIQ_DESCRICAO,ALIQ_PERCENTUAL,ALIQ_CODIGO) VALUES (2,'7 %',7,'02');
INSERT INTO ALIQUOTAS (CP_ALIQUOTAS,ALIQ_DESCRICAO,ALIQ_PERCENTUAL,ALIQ_CODIGO) VALUES (3,'12 %',12,'03');
INSERT INTO ALIQUOTAS (CP_ALIQUOTAS,ALIQ_DESCRICAO,ALIQ_PERCENTUAL,ALIQ_CODIGO) VALUES (4,'SUBSTITUIÇÃO TRIBUTARIA',0,'FF');
INSERT INTO ALIQUOTAS (CP_ALIQUOTAS,ALIQ_DESCRICAO,ALIQ_PERCENTUAL,ALIQ_CODIGO) VALUES (5,'ISENTO',0,'II');
INSERT INTO ALIQUOTAS (CP_ALIQUOTAS,ALIQ_DESCRICAO,ALIQ_PERCENTUAL,ALIQ_CODIGO) VALUES (6,'17 %',17,'04');

COMMIT WORK;
               
