-- Table: public.grupos

create table public.grupos
(
    CP_GRUPOS        SERIAL PRIMARY KEY,
    GRUPO_NOME       character varying (30) NOT NULL,
    GRUPO_COM_SEM    character varying (3)
);

--Dados: public.grupos

INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (1, 'SANDALIAS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (2, 'TAMANCO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (3, 'CHINELO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (4, 'SAPATO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (5, 'TENIS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (6, 'MOCHILA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (7, 'MEIAS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (8, 'MEIAO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (9, 'TORNOZOLEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (10, 'JOELHEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (11, 'COTURNO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (12, 'CHUTEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (13, 'PENALTY ', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (14, 'BOLSA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (15, 'CARTEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (16, 'BOLA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (17, 'CINTO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (18, 'BOLAS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (19, 'BOLSAS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (20, 'BABUCHE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (21, 'BOTINA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (22, 'TAMNCO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (23, 'SAPATILHAS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (24, 'BERMUNDA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (25, 'POCHETE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (26, 'SANDALIA', 'S');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (27, 'SHORT', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (28, 'CINTOS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (29, 'MULE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (30, 'CAMISETA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (31, 'KITS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (32, 'BLUSA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (33, 'SAPATOS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (34, 'MULY', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (35, 'MOLECA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (36, 'BONE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (37, 'BERMUDA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (38, 'SUNGA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (39, 'BOTA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (40, 'TAM ', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (41, 'BOMBA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (42, 'PETECA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (43, 'REDE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (44, 'COXAL', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (45, 'CHANEL', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (46, 'SCARPIN', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (47, 'ESCARPAN ', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (48, 'ESCARPIN', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (49, 'CUECA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (50, 'BUSTIER', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (51, 'BLUSAO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (52, 'CALCA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (53, 'MUNHEQUEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (54, 'ADULTO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (55, 'LUVA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (56, 'CAMISA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (57, 'VESTIDO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (58, 'TOP', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (59, 'FITA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (60, 'SANDALIA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (61, 'MEIA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (62, 'TANGA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (63, 'SUTIÃ', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (64, 'CALÇA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (65, 'REGATA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (66, 'SAIA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (67, 'CALÇAO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (68, 'TORNOZELEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (69, 'JAQUETA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (70, 'CONE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (71, 'MACARRAO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (72, 'SACO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (73, 'MEDALHA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (74, 'APITO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (75, 'MARCACAO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (76, 'TROFEU', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (77, 'CANELEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (78, 'SAPATILHA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (79, 'CALCINHA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (80, 'GORRO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (81, 'CHAPEU', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (82, 'BIKINI', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (83, 'COTOVELEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (84, 'PERFUME', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (85, 'DESODORANTE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (86, 'DEO COLONIA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (87, 'PRODUTO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (88, 'SABONETE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (89, 'EMULSAO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (90, 'LOCAO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (91, 'OLEO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (92, 'MACACAO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (93, 'BLAZER', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (94, 'PALMILHA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (95, 'AMACIANTE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (96, 'CALCANHEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (97, 'IMPERMEABILIZANTE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (98, 'MOCASSIM', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (99, 'SACOLA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (100, 'OUTDOOR', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (101, 'BODY', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (103, 'CATALAGO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (104, 'DISPLAY', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (105, 'MALA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (106, 'APOIO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (107, 'SEGURANÇA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (108, 'NECESSAIRE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (109, 'PAPETE', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (110, 'PASTA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (111, 'FRASQUEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (112, 'ANTI ODOR', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (113, 'PULSEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (114, 'SNEAKERS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (115, 'KEFFOR', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (116, 'SAPATENIS', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (117, 'CORSARIO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (118, 'LIXEIRA', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (119, 'CHAVEIRO', 'C');
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (120, 'ESPUMA LIMPADORA', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (121, 'MAQUIAGEM PARA PERNAS', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (122, 'ALPARGATAS', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (123, 'GEL', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (124, 'OXFORD', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (125, 'WHOOP ', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (126, 'RASTEIRA', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (127, 'SPADRILLES', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (128, 'ANA HICKAMNN', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (129, 'TONALIZANTE', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (130, 'SLIP ON', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (131, 'ANABELA', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (132, 'ESPADRILLE', NULL);
INSERT INTO GRUPOS (CP_GRUPOS, GRUPO_NOME, GRUPO_COM_SEM)
            VALUES (133, 'FLAT', NULL);